-- Seed data for TaskFlow
-- All seed users share the same password: password123
-- Uses pgcrypto crypt() so the hash is generated by the DB (always correct).

INSERT INTO users (id, name, email, password_hash)
SELECT
    id::uuid,
    name,
    email,
    crypt('password123', gen_salt('bf', 12))
FROM (VALUES
    ('00000000-0000-0000-0000-000000000001', 'Test User',   'test@example.com'),
    ('00000000-0000-0000-0000-000000000002', 'Alice Smith', 'alice@example.com'),
    ('00000000-0000-0000-0000-000000000003', 'Bob Jones',   'bob@example.com')
) AS data(id, name, email)
ON CONFLICT (email) DO NOTHING;

INSERT INTO projects (id, name, description, owner_id)
VALUES (
    '00000000-0000-0000-0000-000000000010',
    'Website Redesign',
    'Q2 initiative to modernise the public-facing site',
    '00000000-0000-0000-0000-000000000001'
)
ON CONFLICT DO NOTHING;

INSERT INTO tasks (id, title, description, status, priority, project_id, assignee_id, created_by, due_date)
VALUES
    (
        '00000000-0000-0000-0000-000000000020',
        'Design new homepage',
        'Create mockups and get stakeholder sign-off',
        'todo',
        'high',
        '00000000-0000-0000-0000-000000000010',
        '00000000-0000-0000-0000-000000000002',
        '00000000-0000-0000-0000-000000000001',
        '2026-05-01'
    ),
    (
        '00000000-0000-0000-0000-000000000021',
        'Implement authentication flow',
        'JWT-based login and registration',
        'in_progress',
        'high',
        '00000000-0000-0000-0000-000000000010',
        '00000000-0000-0000-0000-000000000001',
        '00000000-0000-0000-0000-000000000001',
        '2026-04-20'
    ),
    (
        '00000000-0000-0000-0000-000000000022',
        'Set up CI pipeline',
        'GitHub Actions for lint, test, and build',
        'done',
        'medium',
        '00000000-0000-0000-0000-000000000010',
        '00000000-0000-0000-0000-000000000003',
        '00000000-0000-0000-0000-000000000001',
        '2026-04-10'
    )
ON CONFLICT DO NOTHING;
