-- Seed data for TaskFlow
-- All seed users share the same password: password123
-- Uses pgcrypto crypt() so the hash is generated by the DB (always correct).

-- 1. SEED USERS (Indian Vanguard Team)
INSERT INTO users (id, name, email, password_hash)
SELECT
    id::uuid,
    name,
    email,
    crypt('password123', gen_salt('bf', 12))
FROM (VALUES
    ('00000000-0000-0000-0000-000000000001', 'Arjun Mehta',      'test@example.com'),
    ('00000000-0000-0000-0000-000000000002', 'Priya Sharma',     'priya@vanguard.co'),
    ('00000000-0000-0000-0000-000000000003', 'Ishaan Malhotra',  'ishaan@vanguard.co'),
    ('00000000-0000-0000-0000-000000000004', 'Ananya Iyer',      'ananya@vanguard.co'),
    ('00000000-0000-0000-0000-000000000005', 'Rohan Deshmukh',   'rohan@vanguard.co')
) AS data(id, name, email)
ON CONFLICT (email) DO NOTHING;

-- 2. SEED PROJECT (Project Obsidian)
INSERT INTO projects (id, name, description, owner_id)
VALUES (
    '00000000-0000-0000-0000-000000000010',
    'Project Obsidian',
    'Advanced architectural evolution for the Vanguard ecosystem.',
    '00000000-0000-0000-0000-000000000001'
)
ON CONFLICT DO NOTHING;

-- 3. SEED TASKS (Including Critical Overdue for Arjun)
INSERT INTO tasks (id, title, description, status, priority, project_id, assignee_id, created_by, due_date)
VALUES
    -- OVERDUE CRITICAL TASK (To trigger Crimson State)
    (
        '00000000-0000-0000-0000-000000000020',
        'System Health: Kernel Patch',
        'Addressing critical memory performance in the core engine for stability.',
        'todo',
        'high',
        '00000000-0000-0000-0000-000000000010',
        '00000000-0000-0000-0000-000000000001',
        '00000000-0000-0000-0000-000000000001',
        '2026-04-05'
    ),
    (
        '00000000-0000-0000-0000-000000000021',
        'Security Updates: Auth Flow',
        'Refining authentication protocols and security audits for the new release.',
        'in_progress',
        'high',
        '00000000-0000-0000-0000-000000000010',
        '00000000-0000-0000-0000-000000000001',
        '00000000-0000-0000-0000-000000000001',
        '2026-04-15'
    ),
    (
        '00000000-0000-0000-0000-000000000022',
        'Visual Identity: Liquid Mesh',
        'Establishing the new liquid mesh design baseline for the platform.',
        'done',
        'medium',
        '00000000-0000-0000-0000-000000000010',
        '00000000-0000-0000-0000-000000000004',
        '00000000-0000-0000-0000-000000000001',
        '2026-04-09'
    ),
    (
        '00000000-0000-0000-0000-000000000023',
        'Experience Review: Premium UI',
        'Finalizing aesthetic standards and responsiveness for the core navigation.',
        'in_progress',
        'high',
        '00000000-0000-0000-0000-000000000010',
        '00000000-0000-0000-0000-000000000002',
        '00000000-0000-0000-0000-000000000001',
        '2026-04-12'
    )
ON CONFLICT DO NOTHING;
